###################################################
# Makefile for the QCA81XX linux PHY driver
###################################################
TARGET := qca81xx-phy
obj-m += $(TARGET).o
$(TARGET)-objs := qca81xx.o
