###################################################
# Makefile for the QCA8084 linux PHY driver
###################################################
TARGET := qca8084-phy
obj-m += $(TARGET).o
$(TARGET)-objs := qca8084.o
