#SPDX-License-Identifier: GPL-2.0+

obj-y += board_init.o
obj-y += cmd_ipqsmem.o
obj-y += cmd_bootipq.o
obj-$(CONFIG_IPQ_CRASHDUMP) += cmd_crashdump.o
obj-$(CONFIG_IPQ_FLUTILS) += cmd_flutility.o
obj-$(CONFIG_IPQ_FDT_FIXUP) += fdt_fixup.o
obj-y += common.o
obj-y += cmd_ipq.o
