/*
 * Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _QCA807X_PHY_H_
#define _QCA807X_PHY_H_

#ifdef __cplusplus
extern "C"
{
#endif				/* __cplusplus */
enum qca807x_phy_addr_offset {
	QCA807X_PHY_COMBO_ADDR = 4,
	QCA807X_PHY_SERDES_ADDR = 5,
};

/*mii registers*/
#define QCA807X_PHY_MEDIUM_SELECT_STATUS		0x1a
#define QCA807X_PHY_SERDES_RESET_REG		0x0

/*mii registers field*/
#define QCA807X_PHY_INTERFACE_MASK		0xf
#define QCA807X_PHY_INTERFACE_PSGMII		0
#define QCA807X_PHY_INTERFACE_PSGMII_1000BX		1
#define QCA807X_PHY_INTERFACE_PSGMII_100BX		2
#define QCA807X_PHY_INTERFACE_PSGMII_COMBO		3
#define QCA807X_PHY_INTERFACE_QSGMII_SGMII		4
#define QCA807X_PHY_AUTO_COPPER		0x20
#define QCA807X_PHY_AUTO_1000BX		0x10
#define QCA807X_PHY_AUTO_100FX		0x8
#define QCA807X_PHY_SERDES_RESET		0
#define QCA807X_PHY_SERDES_RELEASE		0x5f

/*mmd registers*/
#define QCA807X_PHY_MMD3_ADDR_8023AZ_TIMER_CTRL		0x804e
#define QCA807X_PHY_MMD3_ADDR_CLD_CTRL5		0x8005
#define QCA807X_PHY_MMD3_ADDR_CLD_CTRL3		0x8003
#define QCA807X_PHY_MMD7_LED_100_N_MAP_CTRL		0x8074
#define QCA807X_PHY_MMD7_LED_1000_N_MAP_CTRL		0x8076
#define QCA807X_PHY_MMD7_LED_100_N_FORCE_CTRL		0x8075
#define QCA807X_PHY_MMD7_LED_1000_N_FORCE_CTRL		0x8077
#define QCA807X_PHY_MMD7_FIBER_MODE_AUTO_DETECTION		0x807e

/*mmd registers field*/
#define QCA807X_PHY_MMD3_DAC_AT_BIAS_EN		0x4000
#define QCA807X_PHY_MMD3_VD_HALF_BIAS_EN		0x4000
#define QCA807X_PHY_MMD3_AFE_TX_FULL_AMPLITUDE_EN		0x8000
#define QCA807X_PHY_MMD7_AUTO_DETECTION_EN		1
#define QCA807X_PHY_MMD7_AUTO_DETECTION_1000BX		0x8

int qca807x_phy_ops_init(struct nss_phy_ops *ops);
#ifdef __cplusplus
}
#endif				/* __cplusplus */
#endif				/* _QCA807X_PHY_H_ */
