/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018, The Linux Foundation. All rights reserved.
 *
 * Copyright (c) 2023, Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _DT_BINDINGS_CLK_GCC_IPQ9574_H
#define _DT_BINDINGS_CLK_GCC_IPQ9574_H

/* GCC controlled clock IDs */
#define GCC_BLSP1_UART0_APPS_CLK			0
#define GCC_BLSP1_UART1_APPS_CLK			1
#define GCC_BLSP1_UART2_APPS_CLK			2
#define GCC_BLSP1_AHB_CLK				3
#define GCC_SDCC1_APPS_CLK				4
#define GCC_SDCC1_AHB_CLK				5
#define GCC_BLSP1_QUP1_SPI_APPS_CLK			6
#define GCC_BLSP1_QUP2_SPI_APPS_CLK			7
#define GCC_BLSP1_QUP3_SPI_APPS_CLK			8
#define GCC_BLSP1_QUP4_SPI_APPS_CLK			9
#define GCC_BLSP1_QUP5_SPI_APPS_CLK			10
#define GCC_BLSP1_QUP6_SPI_APPS_CLK			11
#define GCC_NSSNOC_MEMNOC_BFDCD_CLK			12
#define GCC_QDSS_AT_CLK					13
#define GCC_MEM_NOC_NSSNOC_CLK				14
#define GCC_NSSCFG_CLK					15
#define GCC_NSSNOC_ATB_CLK				16
#define GCC_NSSNOC_MEM_NOC_1_CLK			17
#define GCC_NSSNOC_MEMNOC_CLK				18
#define GCC_NSSNOC_QOSGEN_REF_CLK			19
#define GCC_NSSNOC_TIMEOUT_REF_CLK			20
#define GCC_UNIPHY_SYS_CLK				21
#define GCC_PCNOC_BFDCD_CLK				22
#define GCC_SYSTEM_NOC_BFDCD_CLK			23
#define GCC_CMN_12GPLL_AHB_CLK				24
#define GCC_CMN_12GPLL_SYS_CLK				25
#define GCC_MDIO_AHB_CLK				26
#define GCC_NSSNOC_SNOC_CLK				27
#define GCC_NSSNOC_SNOC_1_CLK				28
#define GCC_MEM_NOC_SNOC_AXI_CLK			29
#define GCC_UNIPHY0_SYS_CLK				30
#define GCC_UNIPHY0_AHB_CLK				31
#define GCC_UNIPHY1_SYS_CLK				32
#define GCC_UNIPHY1_AHB_CLK				33
#define GCC_UNIPHY2_SYS_CLK				34
#define GCC_UNIPHY2_AHB_CLK				35
#define GCC_QPIC_IO_MACRO_CLK				36
#define GCC_BLSP1_QUP0_I2C_APPS_CLK			37
#define GCC_BLSP1_QUP1_I2C_APPS_CLK			38
#define GCC_BLSP1_QUP2_I2C_APPS_CLK			39
#define GCC_BLSP1_QUP3_I2C_APPS_CLK			40
#define GCC_BLSP1_QUP4_I2C_APPS_CLK			41
#define GCC_BLSP1_QUP5_I2C_APPS_CLK			42
#define GCC_PCIE_AUX_CLK				43
#define GCC_PCIE0_AXI_M_CLK				44
#define GCC_PCIE0_AXI_S_CLK				45
#define GCC_PCIE0_AHB_CLK				46
#define GCC_PCIE0_AUX_CLK				47
#define GCC_PCIE0_RCHNG_CLK				48
#define GCC_PCIE1_AXI_M_CLK				49
#define GCC_PCIE1_AXI_S_CLK				50
#define GCC_PCIE1_AHB_CLK				51
#define GCC_PCIE1_AUX_CLK				52
#define GCC_PCIE1_RCHNG_CLK				53
#define GCC_PCIE2_AXI_M_CLK				54
#define GCC_PCIE2_AXI_S_CLK				55
#define GCC_PCIE2_AHB_CLK				56
#define GCC_PCIE2_AUX_CLK				57
#define GCC_PCIE2_RCHNG_CLK				58
#define GCC_PCIE3_AXI_M_CLK				59
#define GCC_PCIE3_AXI_S_CLK				60
#define GCC_PCIE3_AHB_CLK				61
#define GCC_PCIE3_AUX_CLK				62
#define GCC_PCIE3_RCHNG_CLK				63
#define GCC_SNOC_PCIE0_1LANE_S_CLK			64
#define GCC_SNOC_PCIE1_1LANE_S_CLK			65
#define GCC_SNOC_PCIE2_2LANE_S_CLK			66
#define GCC_SNOC_PCIE3_2LANE_S_CLK			67
#define GCC_ANOC_PCIE0_1LANE_M_CLK			68
#define GCC_ANOC_PCIE1_1LANE_M_CLK			69
#define GCC_ANOC_PCIE2_2LANE_M_CLK			70
#define GCC_ANOC_PCIE3_2LANE_M_CLK			71
#define GCC_PCIE0_AXI_S_BRIDGE_CLK			72
#define GCC_PCIE1_AXI_S_BRIDGE_CLK			73
#define GCC_PCIE2_AXI_S_BRIDGE_CLK			74
#define GCC_PCIE3_AXI_S_BRIDGE_CLK			75
#define GCC_PCIE0_PIPE_CLK				76
#define GCC_PCIE1_PIPE_CLK				77
#define GCC_PCIE2_PIPE_CLK				78
#define GCC_PCIE3_PIPE_CLK				79
#define GCC_USB0_MASTER_CLK				80
#define GCC_USB0_MOCK_UTMI_CLK				81
#define GCC_USB0_AUX_CLK				82
#define GCC_USB0_PIPE_CLK				83
#define GCC_USB0_SLEEP_CLK				84
#define GCC_SNOC_USB_CLK				85
#define GCC_ANOC_USB_AXI_CLK				86
#define GCC_USB0_PHY_CFG_AHB_CLK			87
#define GCC_BLSP1_UART3_APPS_CLK			88
#define GCC_BLSP1_UART4_APPS_CLK			89
#define GCC_BLSP1_UART5_APPS_CLK			90

/* NSS controlled clock IDs */
#define NSS_CC_CFG_CLK					100
#define NSS_CC_PPE_CLK					101
#define NSS_CC_NSS_CSR_CLK				102
#define NSS_CC_NSSNOC_NSS_CSR_CLK			103
#define NSS_CC_PORT1_MAC_CLK				104
#define NSS_CC_PORT2_MAC_CLK				105
#define NSS_CC_PORT3_MAC_CLK				106
#define NSS_CC_PORT4_MAC_CLK				107
#define NSS_CC_PORT5_MAC_CLK				108
#define NSS_CC_PORT6_MAC_CLK				109
#define NSS_CC_PPE_SWITCH_IPE_CLK			110
#define NSS_CC_PPE_SWITCH_CLK				111
#define NSS_CC_PPE_SWITCH_CFG_CLK			112
#define NSS_CC_PPE_EDMA_CLK				113
#define NSS_CC_PPE_EDMA_CFG_CLK				114
#define NSS_CC_CRYPTO_PPE_CLK				115
#define NSS_CC_NSSNOC_PPE_CLK				116
#define NSS_CC_NSSNOC_PPE_CFG_CLK			117
#define NSS_CC_PPE_SWITCH_BTQ_CLK			118
#define NSS_CC_PORT1_RX_CLK				119
#define NSS_CC_PORT1_TX_CLK				120
#define NSS_CC_PORT2_RX_CLK				121
#define NSS_CC_PORT2_TX_CLK				122
#define NSS_CC_PORT3_RX_CLK				123
#define NSS_CC_PORT3_TX_CLK				124
#define NSS_CC_PORT4_RX_CLK				125
#define NSS_CC_PORT4_TX_CLK				126
#define NSS_CC_PORT5_RX_CLK				127
#define NSS_CC_PORT5_TX_CLK				128
#define NSS_CC_PORT6_RX_CLK				129
#define NSS_CC_PORT6_TX_CLK				130
#define NSS_CC_UNIPHY_PORT1_RX_CLK			131
#define NSS_CC_UNIPHY_PORT1_TX_CLK			132
#define NSS_CC_UNIPHY_PORT2_RX_CLK			133
#define NSS_CC_UNIPHY_PORT2_TX_CLK			134
#define NSS_CC_UNIPHY_PORT3_RX_CLK			135
#define NSS_CC_UNIPHY_PORT3_TX_CLK			136
#define NSS_CC_UNIPHY_PORT4_RX_CLK			137
#define NSS_CC_UNIPHY_PORT4_TX_CLK			138
#define NSS_CC_UNIPHY_PORT5_RX_CLK			139
#define NSS_CC_UNIPHY_PORT5_TX_CLK			140
#define NSS_CC_UNIPHY_PORT6_RX_CLK			141
#define NSS_CC_UNIPHY_PORT6_TX_CLK			142

#define UNIPHY0_NSS_RX_CLK				200
#define UNIPHY0_NSS_TX_CLK				201
#define UNIPHY1_NSS_RX_CLK				202
#define UNIPHY1_NSS_TX_CLK				203
#define UNIPHY2_NSS_RX_CLK				204
#define UNIPHY2_NSS_TX_CLK				205

#endif
